### ISSUE TITLE
Does it work in TinyMCE?

### ISSUE THREAD

**Issue by ZobovV** [zurb/tribute#245]
**Does it work in TinyMCE?**

Tried to add it to editor in different ways, but all of them didn't work.

**Comment by mrsweaters** [comment]
If TinyMCE uses an iframe it might be related to this issue: https://github.com/zurb/tribute/pull/248

Can you try the version in that PR and let me know if that helps?

**Comment by 7obias** [comment]
@mrsweaters  I am trying an integration into TinyMce 3.
I am running into issue #248 

Tribute.js:336 Uncaught DOMException: Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index.
    at Tribute.insertTextAtCursor (http://local.unodc.org/cms/js/bower_components/tribute/dist/tribute.js:379:25)
    at Tribute.showMenuForCollection (http://local.unodc.org/cms/js/bower_components/tribute/dist/tribute.js:346:49)

how can I get the version you mentioned ? I would love to try.

**Comment by 7obias** [comment]
so I think I figured it out.  I tried PR  #248 and #256 which also sounded related. neither worked for me.

```
       key: "insertTextAtCursor",
        value: function insertTextAtCursor(text) {
            var sel, range, html;
            sel = window.getSelection();
            range = sel.getRangeAt(0);
```

the PRs do not seem to touch on the issue I am facing.
TributeRange seems to rely in many places on the gobal window object.  In case the iframe: option is set isn't this an issue?  shouldnt it them be using the iframe's window instead to get the selection range?

**Comment by mrsweaters** [comment]
Thanks for the update @7obias, I think you're on to something about using the global window object for this. We should abstract that out into a `getWindow` method like `getDocument`.

**Comment by 7obias** [comment]
So I went down that path. I pulled getDocument and getWindow up into Tribute.js and used them in places window and document were used directly. 
Now with the proper iframed window reference I still get the same Exception.
I guess there is more to it. maybe related to this https://stackoverflow.com/questions/22935320/uncaught-indexsizeerror-failed-to-execute-getrangeat-on-selection-0-is-not
